### ISSUE TITLE
Help with VS Code client

### ISSUE THREAD

**Issue by pedrorgirardi** [snoe/clojure-lsp#10]
Hi @snoe,

I do some work on a Clojure & ClojureScript extension for VS Code (it's called Calva) and I'm very keen to try the language server, but I didn't manage to get it working.

The server can be found on my path and I can launch the extension, but then I get an 'Internal error'  and I don't find any log.

Could you give me a hand? I really want to see how the server works :)

**Comment by andrestylianos** [comment]
Hi @pedrorgirardi. Are you building from master yourself or using the release binary?

I've just started trying it out with Atom and had a problem with clojure-lsp crashing. A PR was merged last week (https://github.com/snoe/clojure-lsp/pull/9) but there's no new release. Don't know if it's related to the problem you're having but it might be worth a try building from master.

**Comment by pedrorgirardi** [comment]
Hi @andrestylianos, super funny because I'm running from `master` with `lein run`. I must be missing something.

**Comment by andrestylianos** [comment]
Might be something totally unrelated then :confused: 
I'm just getting started with clojure-lsp as well so this was my only guess :stuck_out_tongue:

**Comment by pedrorgirardi** [comment]
Sure, don't worry, It's all good 😀 Thank you, André!

**Comment by snoe** [comment]
@pedrorgirardi The unreleased pr was my suspicion as well. I'll take soon. I am logging to `/tmp/lsp.out` so if you see anything there it could be helpful.

@andrestylianos Thanks for trying to help, I've released your pr.

**Comment by snoe** [comment]
I was unable to reproduce the problem as you described it. 

Did you change the `extension.js` to do a `lein run`. Did you copy the `client-vscode` dir to `~/.vscode/extensions` or run the extension in debug mode? Remember: **vscode will launch the server**, you don't launch it from the terminal. This is the relevant launch line: https://github.com/snoe/clojure-lsp/blob/master/client-vscode/extension.js#L9

Does it crash on all projects/files you open? Does it crash if you clone and open this project?

I noticed I hardcoded the path to `/usr/local/bin/clojure-lsp` (now fixed) but the exception I received in the vscode client when the file was missing was:

```
[Error - 21:03:05] Starting client failed
 Launching server using command /usr/local/bin/clojure-lsp failed.
```

Without the proper `chmod` executable bit set, I received:

```
[Error - 21:07:04] Starting client failed
Error: spawn EACCES
	at exports._errnoException (util.js:1050:11)
	at ChildProcess.spawn (internal/child_process.js:319:11)
	at Object.exports.spawn (child_process.js:390:9)
	at _getServerWorkingDir.then.serverWorkingDir (/Users/case/dev/lsp/client-vscode/node_modules/vscode-languageclient/lib/main.js:346:40)
	at <anonymous>
```

Otherwise I tried with a few different projects (boot and leiningen) and things seemed to work ok.

I suspect I'll need the output of `/tmp/lsp.out` to get further once you are confident it's launching properly.

**Comment by pedrorgirardi** [comment]
@snoe , I just pulled `master`, changed `serverOptions` to point to my **clojure-lsp** and it worked! Thank you very much!

*It works with ClojureScript, so nice! I need to spend some time learning more about this.

**Comment by sfertman** [comment]
@snoe @pedrorgirardi sorry to necromance this thread but... 

I've recently came across this very cool language server and thought I'd try to make a basic vscode extension to support clojure(script) language while learning about the inner workings of clojure and vscode ext mechanism in the process. I'm fairly new to clojurescript (and vscode ext) so this is likely a noob mistake rather than a problem with the server/extension.

Following @pedrorgirardi comment:

>*It works with ClojureScript, so nice! ...

I simply fired up the extension and wrote an `app.cljs` file like so:
```clojure
(ns my.ns.cljs)

(defn print-json
  [m]
  (println (.stringify js/JSON (clj->js m))))
```
but vscode highlighted `js/JSON` and `clj->js` as problems. The hover box showed "Unknown symbol" on both. So, my questions are:
- Is the server binary supposed to support ClojureScript out of the box? 
- Or perhaps I'm supposed to clone the repo and add clojurescript deps in `project.clj` and run it from code with `lein run` like @pedrorgirardi has done (as far as I can tell)? 
- Or perhaps I'm supposed to add `cljs.jar` somewhere on my java classpath?
- Or perhaps the server doesn't support js interop just yet?

Any help or pointer to relevant docs would be greatly appreciated. If there is no friendly beginner docs for this integration, I'd gladly spend some time writing it as I move forward with my project.

Thanks!

**Comment by pedrorgirardi** [comment]
Hi @sfertman .

I think that's a known 'issue' - there are some ClojureScript specific symbols that Clojure LSP doesn't seem to recognize (yet). But what I mean on my comment about a nice ClojureScript support, is that functionalities like symbol navigation and refactoring work for ClojureScript too.

Does it make sense? :)

**Comment by sfertman** [comment]
Thanks @pedrorgirardi, makes sense now. Navigation & refactoring does work well in both clojure and clojurescript.
@snoe, should I open a separate issue for js symbol recognition?

**Comment by snoe** [comment]
@sfertman Yup, interop, especially in clojurescript, hasn't been done yet. An issue to track it would be great.
