### ISSUE TITLE
Multi-arity functions with schema.core/defn

### ISSUE THREAD

**Issue by ericdallo** [snoe/clojure-lsp#108]
The last problem (I hope) I found with `schema.core/defn` is that it `macro-def` does not support `multi-arity` functions like:

![image](https://user-images.githubusercontent.com/7820865/72752192-59770580-3ba0-11ea-9ed7-e51e49746dae.png)

Is this a big problem? or is there some way to change the macro-def adding this support?

Thanks!

**Comment by Luminiscental** [comment]
Looks like there's a disconnect between how `function-signatures` handles stuff versus how the actual references get parsed by `function-params-and-bodies` e.t.c.

maybe want to refactor so that some logic there is shared, in this case it's since parser.clj:562 is only affecting arity diagnostics, not usage diagnostics.

**Comment by snoe** [comment]
Yup, `:function-params-and-bodies` is probably right, I think in the short term it could probably re-use the `:signature-style :typed` to ignore the annotations.

The disconnect between `function-signatures` and `function-params-and-bodies`  e.t.c. is unfortunate - it might be possible that the `:signature` flag on the `:declaration` could add the param references and then we skip adding them later with `:_` or something... 

I think doing `:signature-style` now and doing some hammock time about the disconnect would be fine.
