### ISSUE TITLE
LSP stops to work on project files after go to definition to a internal project function and going back to the last file.

### ISSUE THREAD

**Issue by rafaeldelboni** [snoe/clojure-lsp#184]
LSP stops to work on project files after going to definition to an internal project function and going back to the last file using [jump to previously visited location vim embed function](https://vim.fandom.com/wiki/Jumping_to_previously_visited_locations)

### Versions:
```
vim version: NVIM v0.4.4
node version: v11.15.0
coc.nvim version: 0.0.79-b71489207a
clojure-lsp version: release-20200910T181437 or release-20200911T025911
```

### Diff that probably causes this to happen:
https://github.com/snoe/clojure-lsp/compare/release-20200828T065654...release-20200910T181437

### How to reproduce:
Do a go-to definition to an internal project function then `ctrl+o` to jump back to the original file, then try to do the go-to definition on the same function again, core clojure functions the go to definition still works fine.

### Log:
```
WARN  clojure-lsp.handlers: Finding definition file:///home/delboni/dev/nu/indigo/src/indigo/controllers/challenge.clj row 24 col 48 cursor indigo.logic.challenge/status
WARN  clojure-lsp.main: DidCloseTextDocumentParams
WARN  clojure-lsp.handlers: Finding definition file:///home/delboni/dev/nu/indigo/src/indigo/controllers/challenge.clj row 24 col 48 cursor indigo.logic.challenge/status
WARN  clojure-lsp.handlers: Could not find definition for element under cursor, I think your cursor is: "logic.challenge/status" qualified as: indigo.logic.challenge/status
WARN  clojure-lsp.handlers: Finding definition file:///home/delboni/dev/nu/indigo/src/indigo/controllers/challenge.clj row 24 col 48 cursor indigo.logic.challenge/status
WARN  clojure-lsp.handlers: Could not find definition for element under cursor, I think your cursor is: "logic.challenge/status" qualified as: indigo.logic.challenge/status 
```

**Comment by ericdallo** [comment]
After finding the defintion it's calling `DidCloseTextDocument` for some reason, I'll take a look!

**Comment by ericdallo** [comment]
After some research, the problem is that since the client is sending a [textDocument/didClose](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didClose) because you changed to another file, clojure-lsp is clearing the analyzed documents, and after that release from diff, we cleared some unnecessary variables and that's why you are facing this issue now. 
I could confirm this doesn't happens with Emacs `lsp-mode`.

Now we need to know if this is a expected behavior from the LSP spec, if client should send a didClose notification just because you changed to another buffer
c/c @snoe

**Comment by snoe** [comment]
@ericdallo what was the purpose of clearing the uri file-env on close? https://github.com/snoe/clojure-lsp/commit/2bde0f788da39b7989e57c860f1b1e03e3f4c07e

It seems that even if you do close a buffer, the analysis should be maintained.

**Comment by ericdallo** [comment]
It was for renaming files on client, if we find a way to check if the file was renamed, we can remove it from file-env only when is renamed, WDYT @snoe

**Comment by snoe** [comment]
Yeah, makes sense. 
I think in order to fix this, it looks like we can act optimisticly and clear the file-env within `handlers/rename` when called on a ns. 

Then we can look at workspace.didChangeWatchedFiles and that would be an appropriate place to clear state about the file if there's a `delete` event.

**Comment by ericdallo** [comment]
Hum, it seems a good idea, but I'm not sure how to do that

**Comment by rafaeldelboni** [comment]
Can we change `did-close` to `did-rename` and call it only when a rename happened?

**Comment by ericdallo** [comment]
No @rafaeldelboni, didClose is defined in [LSP spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_didClose) and ATM there is no `didRename`

**Comment by snoe** [comment]
I think it the `dissoc` of `file-envs` and `documents` can be done here with `doc-id` instead of `on-close` https://github.com/snoe/clojure-lsp/blob/7f28cb3e14ab271eb62cc7afb06fee4bcd239087/src/clojure_lsp/handlers.clj#L366 Any reason that wouldn't work?

Although testing it, it feels like rename file is incomplete, I believe all other file-envs likely need to change the fully-qualified symbol when they referenced the renamed thing. Maybe you could take a look @ericdallo and make a new issue if I'm correct there.

**Comment by ericdallo** [comment]
Got it @snoe, thanks for the explanation, I'll take a look later today!

**Comment by ericdallo** [comment]
@rafaeldelboni Could you confirm this was fixed by [release-20200925T220747](https://github.com/snoe/clojure-lsp/releases/tag/release-20200925T220747)?
